[project]
name = "aws-athena-s3-glue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.48",
    "pandas>=2.2.3",
    "pyarrow>=17.0.0",
]
